checkpoint_dir: "/storage/matt_models/inpainting/"

data_path: "/storage/celebA-HQ/celeba_hq_128"
im_size: 128

in_chans: 3
out_chans: 3
batch_size: 25
num_epochs: 100
adv_weight: 0.00003
num_iters_discriminator: 1
gp_weight: 10
drift_weight: 0.001
lr: 0.001
beta_1: 0
beta_2: 0.99
