checkpoint_dir: "/storage/matt_models/mri/"
num_of_top_slices: 8
use-middle-slices: false

calib_width: 16
num_samps: 2
num_z_test: 32
num_z_valid: 8
num_z_train: 2

in_chans: 16
out_chans: 16
num_coils: 8
data_path: "/storage/fastMRI_brain/data"
im_size: 384
R: 8
mask_type: 2

#optimizer:
lr: 0.001
beta_1: 0
beta_2: 0.99
gp_weight: 10

var_weight: 0.012
batch_size: 8
num_epochs: 100